version: '3'

services:
  dynamodb-local:
    container_name: dynamodb-local
    image: amazon/dynamodb-local:latest
    user: root
    command: -jar DynamoDBLocal.jar -sharedDb -inMemory
    ports:
      - 8000:8000
    networks:
      - dynamodb-local-network

  dynamodb-admin:
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=dynamodb-local:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb-local
    networks:
      - dynamodb-local-network

  dynamodb_jankens_migrator:
    image: amazon/aws-cli:latest
    container_name: dynamodb_jankens_migrator
    working_dir: /home/dynamodblocal
    command: dynamodb create-table --cli-input-json file://dynamodb-jankens-migration.json --endpoint-url http://dynamodb-local:8000
    volumes:
      - ./serverless_config:/home/dynamodblocal
    environment:
      - AWS_ACCESS_KEY_ID=unicorn_user
      - AWS_SECRET_ACCESS_KEY=magical_password
      - AWS_DEFAULT_REGION=localhost
    depends_on:
      - dynamodb-local
    networks:
      - dynamodb-local-network
  dynamodb_connections_migrator:
    image: amazon/aws-cli:latest
    container_name: dynamodb_connections_migrator
    working_dir: /home/dynamodblocal
    command: dynamodb create-table --cli-input-json file://dynamodb-connections-migration.json --endpoint-url http://dynamodb-local:8000
    volumes:
      - ./serverless_config:/home/dynamodblocal
    environment:
      - AWS_ACCESS_KEY_ID=unicorn_user
      - AWS_SECRET_ACCESS_KEY=magical_password
      - AWS_DEFAULT_REGION=localhost
    depends_on:
      - dynamodb-local
    networks:
      - dynamodb-local-network

  dynamodb_seeder:
    image: amazon/aws-cli:latest
    container_name: app-dynamodb_seeder
    working_dir: /home/dynamodblocal
    command: dynamodb batch-write-item --request-items file://dynamodb-jankens-seed.json --endpoint-url http://dynamodb-local:8000
    volumes:
      - ./serverless_config:/home/dynamodblocal
    environment:
      - AWS_ACCESS_KEY_ID=unicorn_user
      - AWS_SECRET_ACCESS_KEY=magical_password
      - AWS_DEFAULT_REGION=localhost
    depends_on:
      - dynamodb_jankens_migrator
      - dynamodb-local
    networks:
      - dynamodb-local-network
    restart: on-failure

networks:
  dynamodb-local-network:
    driver: bridge
